ALTER TABLE locations ADD CONSTRAINT chk_locations_latitude CHECK (latitude BETWEEN -90 AND 90);
ALTER TABLE locations ADD CONSTRAINT chk_locations_longitude CHECK (longitude BETWEEN -180 AND 180);
ALTER TABLE users ADD CONSTRAINT chk_users_email_nonblank CHECK (btrim(email) <> '');
ALTER TABLE data_sources ADD CONSTRAINT chk_source_type CHECK (source_type IN ('weather_api', 'IMD', 'NWP', 'historical', 'demo'));
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_temperature CHECK (temperature BETWEEN -100 AND 100);
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_feels_like CHECK (feels_like IS NULL OR feels_like BETWEEN -100 AND 100);
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_humidity CHECK (humidity BETWEEN 0 AND 100);
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_pressure CHECK (pressure IS NULL OR pressure BETWEEN 800 AND 1200);
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_wind_speed CHECK (wind_speed IS NULL OR wind_speed >= 0);
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_wind_direction CHECK (wind_direction IS NULL OR wind_direction >= 0 AND wind_direction < 360);
ALTER TABLE weather_observations ADD CONSTRAINT chk_obs_rainfall CHECK (rainfall >= 0);
ALTER TABLE weather_forecasts ADD CONSTRAINT chk_forecast_temperatures CHECK (min_temperature BETWEEN -100 AND 100 AND max_temperature BETWEEN -100 AND 100 AND min_temperature <= max_temperature);
ALTER TABLE weather_forecasts ADD CONSTRAINT chk_forecast_humidity CHECK (humidity IS NULL OR humidity BETWEEN 0 AND 100);
ALTER TABLE weather_forecasts ADD CONSTRAINT chk_forecast_rain_probability CHECK (rainfall_probability BETWEEN 0 AND 100);
ALTER TABLE weather_forecasts ADD CONSTRAINT chk_forecast_rainfall CHECK (expected_rainfall >= 0);
ALTER TABLE weather_forecasts ADD CONSTRAINT chk_forecast_wind CHECK (wind_speed IS NULL OR wind_speed >= 0);
ALTER TABLE weather_alerts ADD CONSTRAINT chk_alert_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE'));
ALTER TABLE weather_alerts ADD CONSTRAINT chk_alert_period CHECK (end_time > start_time);
ALTER TABLE risk_assessments ADD CONSTRAINT chk_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE'));
ALTER TABLE risk_assessments ADD CONSTRAINT chk_risk_probability CHECK (probability BETWEEN 0 AND 100);
ALTER TABLE agriculture_advisories ADD CONSTRAINT chk_advisory_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE'));
ALTER TABLE agriculture_advisories ADD CONSTRAINT chk_advisory_period CHECK (valid_until > valid_from);
ALTER TABLE climate_data ADD CONSTRAINT chk_climate_year CHECK (year BETWEEN 1800 AND 2200);
ALTER TABLE climate_data ADD CONSTRAINT chk_climate_month CHECK (month BETWEEN 1 AND 12);
ALTER TABLE climate_data ADD CONSTRAINT chk_climate_temperatures CHECK (minimum_temperature BETWEEN -100 AND 100 AND maximum_temperature BETWEEN -100 AND 100 AND average_temperature BETWEEN -100 AND 100 AND minimum_temperature <= average_temperature AND average_temperature <= maximum_temperature);
ALTER TABLE climate_data ADD CONSTRAINT chk_climate_rainfall CHECK (rainfall >= 0);
ALTER TABLE climate_data ADD CONSTRAINT chk_climate_humidity CHECK (humidity IS NULL OR humidity BETWEEN 0 AND 100);
